language: node_js
node_js:
  - "stable"
cache: npm

install:
  - npm ci
  
before_script:
  - npm install grunt-cli -g

script:
  - CI='' npm run
 
deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: covid-hull-unsaac
  skip-cleanup: true
