language: node_js
node_js:
  - "stable"
cache: npm

before_script:
  - npm install grunt-cli -g
  
install:
  - npm ci
  
script:
  - CI='' npm run build
 
deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: covid-hull-unsaac
  skip-cleanup: true
